apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resize.fullname" . }}
  namespace: {{ .Values.namespace | default "app" }}
  labels:
    {{- include "resize.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "resize.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "resize.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: app
        image: "{{ include "resize.imageRepository" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: metrics
        {{- if .Values.env }}
        env:
          {{- toYaml .Values.env | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
