apiVersion: v1
kind: Service
metadata:
  name: {{ include "resize.fullname" . }}
  namespace: {{ .Values.namespace | default "go" }}
  labels:
    {{- include "resize.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    {{- include "resize.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: 8080
